import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {createEncryptedPromotionIntake,registerPromotionIntake} from './promotion-intake.js';
function fixture(retry=false){const rows=new Map();let active=0;const database={ref:path=>{let warm=false;return {get:async()=>({val:()=>rows.get(path)||null}),on:(_event,fn)=>{warm=true;active++;queueMicrotask(fn);},off:()=>{warm=false;active--;},transaction:async fn=>{let next=fn(warm?rows.get(path)||null:null);if(retry&&next!==undefined)next=fn(next);if(next!==undefined)rows.set(path,next);return {committed:next!==undefined,snapshot:{val:()=>rows.get(path)||null}};}};}};return {rows,database,store:createEncryptedPromotionIntake(database,'secret'.repeat(10)),active:()=>active};}
test('cold references retain server state and detach listeners',async()=>{const f=fixture(true);await f.store.transaction('123',()=>({lease:{id:'mine'},messages:[]}));const result=await f.store.transaction('123',row=>{if(row.lease?.id!=='mine')return;row.messages=[{text:'answer'}];return row;});assert.equal(result.committed,true);assert.equal(result.value.messages[0].text,'answer');assert.equal(f.active(),0);await assert.rejects(f.store.transaction('123',()=>{throw Error('failure');}));assert.equal(f.active(),0);});
test('encrypted intake hides text, isolates owners and rejects tampering',async()=>{const f=fixture();await f.store.transaction('123',()=>({messages:[{text:'private request'}]}));assert.equal(JSON.stringify([...f.rows.values()]).includes('private request'),false);assert.equal((await f.store.get('123')).messages[0].text,'private request');assert.deepEqual(await f.store.get('456'),{});const [path,row]=[...f.rows][0];f.rows.set(path,{...row,data:'AAAA'});await assert.rejects(f.store.get('123'),{status:503});});
test('session requires verified token, message retries are idempotent and persist after recreation',async()=>{const f=fixture(),app=express();registerPromotionIntake(app,{store:f.store,env:{PROMOTION_INTAKE_ENABLED:'true'},authenticate:async(token,id)=>{if(id!=='123')throw Object.assign(Error('owner mismatch'),{status:401});return {id,name:'Business'}}});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const url=`http://127.0.0.1:${server.address().port}/api/promotion`;assert.equal((await fetch(url+'/session')).status,401);const headers={Authorization:'Promotion '+'x'.repeat(43),'X-MyCity-User-Id':'123',Origin:'gbcustom://app'};for(let i=0;i<2;i++){const body=new FormData();body.set('text','Promocionar mi negocio');body.set('clientRequestId','test-request');const r=await fetch(url+'/messages',{method:'POST',headers,body});assert.equal(r.status,200);assert.equal((await r.json()).messages.length,2);}const reopened=createEncryptedPromotionIntake(f.database,'secret'.repeat(10));assert.equal((await reopened.get('123')).messages.length,2);assert.equal((await fetch(url+'/session',{headers:{...headers,'X-MyCity-User-Id':'456'}})).status,401);}finally{await new Promise(r=>server.close(r));}});
test('assistant receives only owner history and stores validated draft without activating publication',async()=>{const f=fixture(true),app=express();let calls=0;registerPromotionIntake(app,{store:f.store,env:{PROMOTION_INTAKE_ENABLED:'true',PROMOTION_AI_ENABLED:'true',OPENAI_API_KEY:'test',PROMOTION_AI_MODEL:'test'},authenticate:async()=>({id:'123',name:'Business'}),assistant:async({messages})=>{calls++;assert.equal(messages.length,1);return {reply:'Usaré ambos. ¿Qué ofreces?',business:{commercialName:'Test',verificationStatus:'verified'},campaign:{audience:'both',days:[1],time:'10:00',timezone:'America/New_York'}};}});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const url=`http://127.0.0.1:${server.address().port}/api/promotion`;const headers={Authorization:'Promotion '+'x'.repeat(43),'X-MyCity-User-Id':'123'};for(let i=0;i<2;i++){const body=new FormData();body.set('text','Ambos');body.set('clientRequestId','ai-request');const r=await fetch(url+'/messages',{method:'POST',headers,body});assert.equal(r.status,200);assert.equal((await r.json()).messages[1].text,'Usaré ambos. ¿Qué ofreces?');}assert.equal(calls,1);const row=await f.store.get('123');assert.equal(row.business.verificationStatus,'pending');assert.equal(row.campaign.draft.audience,'both');assert.equal(row.campaign.status,'draft');assert.deepEqual(await f.store.get('456'),{});}finally{await new Promise(r=>server.close(r));}});
