import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import Stripe from 'stripe';
import {createPromotionBilling,hasPromotionAccess,registerPromotionPaymentWebhook} from './promotion-billing.js';
function fixture(){let row={preparation:{confirmedFingerprint:'confirmed'}};const owners=new Map();const store={get:async()=>structuredClone(row),transaction:async(_,fn)=>{const next=fn(structuredClone(row));if(next)row=next;return {committed:!!next,value:structuredClone(row)};},bindCustomer:async(c,o)=>owners.set(c,o),ownerForCustomer:async c=>owners.get(c)};let sessions=0;const stripe={accounts:{retrieve:async()=>({id:'acct_myc'})},prices:{retrieve:async()=>({id:'price_myc',active:true,currency:'usd',unit_amount:999,recurring:{interval:'month',interval_count:1}})},customers:{create:async()=>({id:'cus_myc'})},subscriptions:{list:async()=>({data:[]}),retrieve:async()=>({id:'sub_myc',customer:'cus_myc',status:'trialing',trial_start:10,trial_end:Date.now()/1000+500,items:{data:[{price:{id:'price_myc'}}]}})},checkout:{sessions:{create:async params=>{assert.equal(params.mode,'subscription');assert.equal(params.subscription_data.trial_period_days,14);assert.equal(params.payment_method_types,undefined);sessions++;return {id:'cs_myc',url:'https://checkout.stripe.com/test'};},retrieve:async()=>({id:'cs_myc',status:'open',url:'https://checkout.stripe.com/test'})}},webhooks:new Stripe('test').webhooks};const env={PROMOTION_STRIPE_ACCOUNT_ID:'acct_myc',PROMOTION_STRIPE_PRICE_ID:'price_myc',PROMOTION_STRIPE_WEBHOOK_SECRET:'test_signing_secret',PROMOTION_PUBLIC_URL:'https://www.mycity.city/promotion'};return {store,stripe,env,row:()=>row,sessions:()=>sessions,billing:createPromotionBilling({store,stripe,env})};}
test('checkout validates merchant, reuses open session and grants nothing before Stripe synchronization',async()=>{const f=fixture();await f.billing.checkout({id:'123',name:'Test'});assert.equal(hasPromotionAccess(f.row().billing),false);await f.billing.checkout({id:'123',name:'Test'});assert.equal(f.sessions(),1);await f.billing.syncSubscription('sub_myc');assert.equal(hasPromotionAccess(f.row().billing),true);f.env.PROMOTION_STRIPE_ACCOUNT_ID='wrong';await assert.rejects(f.billing.validate(),{status:503});});
test('signed webhook before JSON parser synchronizes lifecycle; forged signature cannot grant access',async()=>{const f=fixture();await f.billing.checkout({id:'123',name:'Test'});const app=express();registerPromotionPaymentWebhook(app,f);app.use(express.json());const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const body=JSON.stringify({id:'evt_myc',type:'customer.subscription.updated',data:{object:{id:'sub_myc'}}});const url='http://127.0.0.1:'+server.address().port+'/api/promotion/stripe/webhook';assert.equal((await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':'forged'},body})).status,400);const sig=f.stripe.webhooks.generateTestHeaderString({payload:body,secret:f.env.PROMOTION_STRIPE_WEBHOOK_SECRET});assert.equal((await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':sig},body})).status,200);assert.equal(hasPromotionAccess(f.row().billing),true);}finally{await new Promise(r=>server.close(r));}});
test('expired, delinquent and collection-paused subscriptions do not grant publishing access',()=>{for(const b of [{status:'active',expiresAt:1},{status:'past_due',expiresAt:Date.now()+1000},{status:'trialing',expiresAt:Date.now()+1000,collectionPaused:true}])assert.equal(hasPromotionAccess(b),false);});
