import test from 'node:test';
import assert from 'node:assert/strict';
import {createPromotionEmailAuth,registeredPromotionAccount,sendPromotionVerification} from './promotion-email-auth.js';
function fixture(){let time=1000000;const rows=new Map();let delivery;const store={get:async p=>rows.get(p),set:async(p,v)=>{v===null?rows.delete(p):rows.set(p,structuredClone(v));},transaction:async(p,fn)=>{const value=fn(structuredClone(rows.get(p)));if(value===undefined)return {committed:false,value:rows.get(p)};rows.set(p,structuredClone(value));return {committed:true,value};}};const env={PROMOTION_EMAIL_AUTH_ENABLED:'true',PROMOTION_AUTH_STORAGE_PRIVATE:'true',PROMOTION_EMAIL_AUTH_SECRET:'x'.repeat(32)};const auth=createPromotionEmailAuth({store,env,now:()=>time,lookup:async id=>({id,email:'registered@example.com',name:'Business',admin:false}),deliver:async data=>{delivery=data}});return {auth,rows,env,store,get delivery(){return delivery},advance:ms=>time+=ms};}
test('only registered email is sent; code creates expiring owner-bound revocable session',async()=>{const f=fixture();const challenge=await f.auth.start('123','ip');assert.equal(f.delivery.recipientEmail,'registered@example.com');const verified=await f.auth.confirm(challenge.challengeId,f.delivery.verificationCode,'123','ip');assert.equal((await f.auth.authenticate(verified.accessToken,'123')).id,'123');await assert.rejects(f.auth.authenticate(verified.accessToken,'456'),{status:401});await assert.rejects(f.auth.confirm(challenge.challengeId,f.delivery.verificationCode,'123','ip'),{status:401});assert.ok(!JSON.stringify([...f.rows.values()]).includes(verified.accessToken));await f.auth.logout(verified.accessToken);await assert.rejects(f.auth.authenticate(verified.accessToken,'123'),{status:401});});
test('five incorrect attempts lock the code even if the next code is correct',async()=>{const f=fixture(),c=await f.auth.start('123','ip');const wrong=f.delivery.verificationCode==='000000'?'000001':'000000';for(let i=0;i<5;i++)await assert.rejects(f.auth.confirm(c.challengeId,wrong,'123','ip'),{status:401});await assert.rejects(f.auth.confirm(c.challengeId,f.delivery.verificationCode,'123','ip'),{status:401});});
test('challenge expires after ten minutes and owner mismatch never consumes correct code',async()=>{const f=fixture(),c=await f.auth.start('123','ip');await assert.rejects(f.auth.confirm(c.challengeId,f.delivery.verificationCode,'456','ip'),{status:401});f.advance(600001);await assert.rejects(f.auth.confirm(c.challengeId,f.delivery.verificationCode,'123','ip'),{status:401});});
test('concurrent confirmation grants only one session',async()=>{const f=fixture(),c=await f.auth.start('123','ip');const outcomes=await Promise.allSettled([f.auth.confirm(c.challengeId,f.delivery.verificationCode,'123','ip'),f.auth.confirm(c.challengeId,f.delivery.verificationCode,'123','ip')]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);});
test('resend cooldown blocks repeat requests',async()=>{const f=fixture();await f.auth.start('123','ip');await assert.rejects(f.auth.start('123','ip'),{status:429});});
test('unconfirmed delivery deletes the unusable challenge',async()=>{const f=fixture();const auth=createPromotionEmailAuth({store:f.store,env:f.env,lookup:async id=>({id,email:'registered@example.com'}),deliver:async()=>{throw Error('mail failed')}});await assert.rejects(auth.start('123','ip'),{status:503});assert.equal([...f.rows.keys()].filter(x=>x.startsWith('promotionAuthChallenges/')).length,0);});
test('upstream must return the requested identifier',async()=>{const env={GOODBARBER_APP_ID:'2817182',GOODBARBER_READ_TOKEN:'server-secret'};let request;await assert.rejects(registeredPromotionAccount('123',{env,fetchImpl:async(url,options)=>{request={url,options};return{ok:true,json:async()=>({user_id:456,email:'other@example.com'})}}}),{status:503});assert.ok(request.url.endsWith('/prospect/123/'));assert.equal(request.options.headers.token,'server-secret');});
test('Make accepted webhook is insufficient: require matching sent acknowledgement',async()=>{const env={PROMOTION_VERIFICATION_WEBHOOK_URL:'https://hook.us1.make.com/test',PROMOTION_VERIFICATION_WEBHOOK_KEY:'key'};await assert.rejects(sendPromotionVerification({challengeId:'a'},{env,fetchImpl:async()=>({ok:true,json:async()=>({status:'accepted'})})}),{status:503});await sendPromotionVerification({challengeId:'a'},{env,fetchImpl:async()=>({ok:true,json:async()=>({status:'sent',challengeId:'a'})})});});

test('expired members resolve by exact user ID across subscription pages',async()=>{
 const env={GOODBARBER_APP_ID:'2817182',GOODBARBER_READ_TOKEN:'secret'};const paths=[];
 const account=await registeredPromotionAccount('433069',{env,fetchImpl:async url=>{
 paths.push(url);if(url.includes('/prospect/'))return {ok:false,status:404};
 const subscriptions=url.includes('/expired/')&&url.includes('page=2&')?[{id:178681,user:{id:433069,email:'registered@example.com',first_name:'Cart',last_name:'Ready'}}]:[{id:433069,user:{id:456,email:'other@example.com'}}];
 return {ok:true,status:200,json:async()=>({subscriptions,next:url.includes('/expired/')&&url.includes('page=1&')?'next':null})};
 }});assert.equal(account.id,'433069');assert.equal(account.email,'registered@example.com');assert.equal(paths.length,4);
});
test('permission failures never fall back to membership lists',async()=>{
 let calls=0;await assert.rejects(registeredPromotionAccount('123',{env:{GOODBARBER_APP_ID:'2817182',GOODBARBER_READ_TOKEN:'secret'},fetchImpl:async()=>{calls++;return {ok:false,status:403,json:async()=>({error_code:1998})}}}),{status:503});assert.equal(calls,1);
});
